%YAML:1.0
# data
dataset_dir: /media/xiang/Data/Dataset/Kitti/dataset/sequences/00

#camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camear.cy: 249.7

num_features: 150
num_features_init: 50
num_features_tracking: 50